"""
    This software is licensed under the Draconic Free License version 1. Refer
    to LICENSE.txt for more information.

    Copyright (c) 2021 Draconic Entity
"""

config_setting(
    name = "mem-arena",
    define_values = {
        "mem": "arena"
    }
)

config_setting(
    name = "mem-malloc",
    define_values = {
        "mem": "malloc"
    }
)

config_setting(
    name = "no-intrinsics",
    define_values = {
        "intrinsics": "off"
    }
)

config_setting(
    name = "intrinsics",
    define_values = {
        "intrinsics": "on"
    }
)
