
load("@rules_foreign_cc//tools/build_defs:cmake.bzl", "cmake_external")

"""
./lib/libosgUI.so
./lib/libosgParticle.so
./lib/libosgGA.so
./lib/libosgManipulator.so
./lib/libosgShadow.so
./lib/libosgWidget.so
./lib/libosgPresentation.so
./lib/libosgText.so
./lib/libosgFX.so
./lib/libosgTerrain.so
./lib/libosgViewer.so
./lib/libOpenThreads.so
./lib/libosgVolume.so
./lib/libosgUtil.so
./lib/libosgSim.so
./lib/osgPlugins-3.7.0/osgdb_cfg.so
./lib/osgPlugins-3.7.0/osgdb_serializers_osg.so
./lib/osgPlugins-3.7.0/osgdb_serializers_osgui.so
./lib/osgPlugins-3.7.0/osgdb_osgviewer.so
./lib/osgPlugins-3.7.0/osgdb_osgjs.so
./lib/osgPlugins-3.7.0/osgdb_3ds.so
./lib/osgPlugins-3.7.0/osgdb_serializers_osgparticle.so
./lib/osgPlugins-3.7.0/osgdb_serializers_osgutil.so
./lib/osgPlugins-3.7.0/osgdb_deprecated_osgterrain.so
./lib/osgPlugins-3.7.0/osgdb_ive.so
./lib/osgPlugins-3.7.0/osgdb_deprecated_osg.so
./lib/osgPlugins-3.7.0/osgdb_serializers_osganimation.so
./lib/osgPlugins-3.7.0/osgdb_dot.so
./lib/osgPlugins-3.7.0/osgdb_ktx.so
./lib/osgPlugins-3.7.0/osgdb_x.so
./lib/osgPlugins-3.7.0/osgdb_openflight.so
./lib/osgPlugins-3.7.0/osgdb_serializers_osgviewer.so
./lib/osgPlugins-3.7.0/osgdb_osg.so
./lib/osgPlugins-3.7.0/osgdb_deprecated_osgparticle.so
./lib/osgPlugins-3.7.0/osgdb_deprecated_osgviewer.so
./lib/osgPlugins-3.7.0/osgdb_deprecated_osgwidget.so
./lib/osgPlugins-3.7.0/osgdb_bsp.so
./lib/osgPlugins-3.7.0/osgdb_pvr.so
./lib/osgPlugins-3.7.0/osgdb_serializers_osgterrain.so
./lib/osgPlugins-3.7.0/osgdb_pov.so
./lib/osgPlugins-3.7.0/osgdb_deprecated_osgshadow.so
./lib/osgPlugins-3.7.0/osgdb_lwo.so
./lib/osgPlugins-3.7.0/osgdb_osga.so
./lib/osgPlugins-3.7.0/osgdb_md2.so
./lib/osgPlugins-3.7.0/osgdb_scale.so
./lib/osgPlugins-3.7.0/osgdb_mdl.so
./lib/osgPlugins-3.7.0/osgdb_gz.so
./lib/osgPlugins-3.7.0/osgdb_serializers_osgshadow.so
./lib/osgPlugins-3.7.0/osgdb_obj.so
./lib/osgPlugins-3.7.0/osgdb_serializers_osgmanipulator.so
./lib/osgPlugins-3.7.0/osgdb_pic.so
./lib/osgPlugins-3.7.0/osgdb_serializers_osgfx.so
./lib/osgPlugins-3.7.0/osgdb_p3d.so
./lib/osgPlugins-3.7.0/osgdb_stl.so
./lib/osgPlugins-3.7.0/osgdb_rgb.so
./lib/osgPlugins-3.7.0/osgdb_bvh.so
./lib/osgPlugins-3.7.0/osgdb_lws.so
./lib/osgPlugins-3.7.0/osgdb_serializers_osgsim.so
./lib/osgPlugins-3.7.0/osgdb_pnm.so
./lib/osgPlugins-3.7.0/osgdb_deprecated_osgvolume.so
./lib/osgPlugins-3.7.0/osgdb_vtf.so
./lib/osgPlugins-3.7.0/osgdb_dds.so
./lib/osgPlugins-3.7.0/osgdb_ply.so
./lib/osgPlugins-3.7.0/osgdb_freetype.so
./lib/osgPlugins-3.7.0/osgdb_deprecated_osganimation.so
./lib/osgPlugins-3.7.0/osgdb_dxf.so
./lib/osgPlugins-3.7.0/osgdb_tf.so
./lib/osgPlugins-3.7.0/osgdb_osc.so
./lib/osgPlugins-3.7.0/osgdb_hdr.so
./lib/osgPlugins-3.7.0/osgdb_logo.so
./lib/osgPlugins-3.7.0/osgdb_rot.so
./lib/osgPlugins-3.7.0/osgdb_revisions.so
./lib/osgPlugins-3.7.0/osgdb_trans.so
./lib/osgPlugins-3.7.0/osgdb_shp.so
./lib/osgPlugins-3.7.0/osgdb_tgz.so
./lib/osgPlugins-3.7.0/osgdb_bmp.so
./lib/osgPlugins-3.7.0/osgdb_trk.so
./lib/osgPlugins-3.7.0/osgdb_glsl.so
./lib/osgPlugins-3.7.0/osgdb_txf.so
./lib/osgPlugins-3.7.0/osgdb_gles.so
./lib/osgPlugins-3.7.0/osgdb_zip.so
./lib/osgPlugins-3.7.0/osgdb_osgtgz.so
./lib/osgPlugins-3.7.0/osgdb_deprecated_osgsim.so
./lib/osgPlugins-3.7.0/osgdb_tga.so
./lib/osgPlugins-3.7.0/osgdb_deprecated_osgtext.so
./lib/osgPlugins-3.7.0/osgdb_normals.so
./lib/osgPlugins-3.7.0/osgdb_3dc.so
./lib/osgPlugins-3.7.0/osgdb_osgterrain.so
./lib/osgPlugins-3.7.0/osgdb_lua.so
./lib/osgPlugins-3.7.0/osgdb_deprecated_osgfx.so
./lib/osgPlugins-3.7.0/osgdb_png.so
./lib/osgPlugins-3.7.0/osgdb_osgshadow.so
./lib/osgPlugins-3.7.0/osgdb_serializers_osgvolume.so
./lib/osgPlugins-3.7.0/osgdb_serializers_osgtext.so
./lib/osgPlugins-3.7.0/osgdb_txp.so
./lib/osgPlugins-3.7.0/osgdb_serializers_osgga.so
./lib/osgPlugins-3.7.0/osgdb_ac.so
./lib/libosgAnimation.so
./lib/libosgDB.so
./lib/libosg.so
"""

cmake_external(
   name = "library",
   lib_source = "@osg//:.",
   shared_libraries = [
       "libosg.so"
   ]
)
