local_repository(
    name = "kge",
    path = "{BUILD_WORKSPACE_DIRECTORY}"
)

load("@kge//:repositories.bzl", "repositories")
repositories()

load("@rules_foreign_cc//:workspace_definitions.bzl", "rules_foreign_cc_dependencies")
rules_foreign_cc_dependencies()

load("@rules_pkg//:deps.bzl", "rules_pkg_dependencies")
rules_pkg_dependencies()
