local_repository(
    name = "kge",
    path = "{BUILD_WORKSPACE_DIRECTORY}"
)

load("@kge//:repositories.bzl", "repositories")
repositories()

load("@kge//:dependencies.bzl", "dependencies")
dependencies()
