"""
    This software is licensed under the Draconic Free License version 1. Refer
    to LICENSE.txt for more information.

    Copyright (c) 2021 Draconic Entity
"""

cc_test(
    name = "tests",
    srcs = glob(
        include=["**/*.cpp"],
    ),
    deps = [
        "//components/support:support",
        "@gtest//:gtest"
    ]
)
